id: IF4E3F4EF
ocr_import_info:
  timestamp: '2023-09-27T04:30:59.562478+00:00'
  batch_id: batch-c5df
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 06:21:33.505457+00:00
last_modified: 2023-09-27 06:21:33.505464+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM4068
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM4068
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་སྣང་བའི་བརྗེད་ཐོ།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.8773987848006543
  ocr_word_median_confidence_index: 0.941318985
bases:
  I1NLM4068_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM4068_001
      total_pages: 590
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM4068_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.941318985
      ocr_word_mean_confidence_index: 0.8773987848006543
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
